---
- name: Set configuration directory path
  file:
    path: "{{ influxdb_configuration_dir }}"
    state: directory

- name: Set templatized InfluxDB configuration
  template: 
    src: influxdb.conf.j2 
    dest: "{{ influxdb_configuration_dir }}/influxdb.conf"
    force: yes
    backup: yes
    owner: influxdb
    group: influxdb
    mode: 0744
  when: influxdb_template_configuration
