- hosts: localhost
  become: yes
  tasks:
  - name: install iperf3
    yum:
      name: iperf3
  - name: "create iperf user to run service"
    user: name=iperf shell=/sbin/nologin
  - name: "install iperf3 unit file for systemd"
    template:
      dest: /etc/systemd/system/iperf3.service
      src: templates/iperf3.service.j2
  - name: "enable and start iperf3 service"
    systemd:
      daemon_reload: true
      enabled: true
      name: iperf3
      state: started