- hosts: localhost
  connection: local
  tasks:
    - name: Install OC package
      become: yes
      yum:
        name: "{{oneclient_package}}"
    - name: Set FUSE allow_other
      become: yes
      lineinfile:
        regexp: ".*user_allow_other"
        line: user_allow_other
        path: /etc/fuse.conf
    - name: Create /tmp/mntoc
      file:
        name: /tmp/mntoc
        state: directory
    - name: Mount oneclient 
      shell: "oneclient -H {{oneprovider}} -t {{access_token}} /tmp/mntoc -i -o allow_other --force-direct-io --force-fullblock-read -v 1 --rndrd-prefetch-cluster-window=12582912 --rndrd-prefetch-cluster-block-threshold=5  --cluster-prefetch-threshold-random --prefetch-mode-async --monitoring-type graphite --monitoring-level-full --provider-timeout=400  --monitoring-period 5 --graphite-url tcp://{{grafana_ip}}:2003 --graphite-namespace-prefix oneclient-op-ceph"
