- hosts: clients
  tasks:
    - name: Add public keys
      become: no
      authorized_key:
        user: "{{ansible_env.USER}}"
        key: "{{ lookup('file', 'pubkeys') }}"
    - name: Core pattern
      become: yes
      sysctl:
        name: kernel.core_pattern
        value: "| /usr/lib/systemd/systemd-coredump %p %u %g %s %t %c %e"
    - name: Check for docker
      stat:
        path: /usr/bin/docker
      register: ds
    - name: Install docker
      shell: curl --tlsv1 -sSL https://get.docker.com/ | sh
      when: ds.stat.exists == False
    - name: Start docker
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Install OC package
      become: yes
      yum:
        name: "{{oneclient_package}}"
    - name: Set FUSE allow_other
      become: yes
      lineinfile:
        regexp: ".*user_allow_other"
        line: user_allow_other
        path: /etc/fuse.conf
    - name: Change MaxSessions for sshd
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^MaxSessions"
        line: "MaxSessions 500"
    - name: Change MaxStartups for sshd
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^MaxStartups"
        line: "MaxStartups 500"
    - name: Restart sshd
      become: yes
      systemd:
        name: sshd
        state: restarted
    - name: Unmount oneclient
      command: "oneclient -u /tmp/mntoc"
      ignore_errors: yes
    - name: Create /tmp/mntoc
      file:
        name: /tmp/mntoc
        state: directory
    - name: Trying to mount oneclient 
      shell: "oneclient -H {{oneprovider}} -t {{access_token}} /tmp/mntoc -i -o allow_other --force-direct-io --force-fullblock-read -v 1 --rndrd-prefetch-cluster-window=12582912 --rndrd-prefetch-cluster-block-threshold=5  --cluster-prefetch-threshold-random --monitoring-type graphite --monitoring-level-full --provider-timeout=30  --monitoring-period 5 --graphite-url tcp://{{grafana_ip}}:2003 --graphite-namespace-prefix $(hostname|cut -f1 -d.)"
      register: res
      until: res.rc == 0
      retries: 12
      delay: 10
    - name: Save oneclient command
      copy:
        content: "oneclient -H {{oneprovider}} -t {{access_token}} /tmp/mntoc -i -o allow_other --force-direct-io --force-fullblock-read -v 1 --rndrd-prefetch-cluster-window=12582912 --rndrd-prefetch-cluster-block-threshold=5  --cluster-prefetch-threshold-random --monitoring-type graphite --monitoring-level-full --provider-timeout=30  --monitoring-period 5 --graphite-url tcp://{{grafana_ip}}:2003 --graphite-namespace-prefix $(hostname|cut -f1 -d.)"
        dest: /tmp/oneclient.sh
        mode: 0755
